### PR TITLE
Implement PEXPIREAT w/tests, update docs, bump version

### PR DESCRIPTION
**Pull request by aviddiviner**
Hi. Me again. 😄 I took the liberty of bumping the version, if you want to push this to PyPI.
Cheers.

### CODE REVIEW

**Comment by aviddiviner** [comment]
I found a rounding error with millisecond expires too, added some tests and a fix for that now.

**Comment by jamesls** [comment]
Thanks for the pull request, would you mind reverting the version bump change?  I'd like to try to pull in a few more changes before pushing out a new release.  I will get a release out soon though.

**Comment by aviddiviner** [comment]
Sure, no worries, done.

**Comment by jamesls** [comment]
Thanks.

**Pull request merged**
