### PR TITLE
_check_conn: handle AttributeError with mocked func

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/jamesls/fakeredis/issues/200.

### CODE REVIEW

**Comment by bmerry** [comment]
I'm not a big fan of this - I feel like this is adding more magic to fix the problems of the initial magic. I'll see if I can come up with something that solves your problem with less magic instead of more.

**Comment by blueyed** [comment]
Agreed.
I will try your suggestions in #200, and maybe something like this is not needed than at all?
(but it certainly was confusing when trying to upgrade fakeredis with my current mocking approach)

**Comment by bmerry** [comment]
Yes, if you can fix this from the outside using my suggestions in #200 then I'd be happiest to make no changes at all.

**Comment by blueyed** [comment]
autospec=True works: https://github.com/jamesls/fakeredis/issue_comments#issuecomment-412081913

**Pull request closed without merging**
