### PR TITLE
Fix TTL/EXPIRE, implement PEXPIRE and add tests.

### PR DESCRIPTION
**Pull request by aviddiviner**
*(Resubmitted for Travis.)*

I had a look at how you did TTL / PTTL and did the same thing here. Added tests which now pass.

The second commit is just me removing some trailing whitespace and little formatting fixes (my pep8 linter complained), and there was one test which was duplicated that I removed. 😃

### CODE REVIEW

**Comment by aviddiviner** [comment]
Today I found some errors in how fakeredis handles EXPIRE and TTL. I've added some tests and fixed the errors. I'm just adding it in to this pull request.

**Comment by aviddiviner** [comment]
Ping. :)

**Comment by jamesls** [comment]
Sorry for the delay, I'll take a look at this today.

**Comment by aviddiviner** [comment]
Thanks, much appreciated.

**Comment by jamesls** [comment]
Thanks for the pull request.

**Pull request merged**
