### PR TITLE
support scan command, return 0 and all keys match the pattern

### PR DESCRIPTION
**Pull request by liamchzh**
http://redis.io/commands/scan

### CODE REVIEW

**Comment by jamesls** [comment]
Thanks, per the [contributing guidelines](https://github.com/jamesls/fakeredis/blob/master/CONTRIBUTING.rst), new features require unit tests before merging.  If you could update the PR with tests I'd be happy to merge.

**Comment by liamchzh** [comment]
Tests failed. But it works on my Mac OS and Debian system.

**Comment by jamesls** [comment]
Interesting.  We'll need to get a clean run through travis before merging.  I'll try to take a look at this in the next couple of days, unless of course you beat me to it.

**Comment by liamchzh** [comment]
Thanks.

**Comment by btashton** [comment]
I extended this in PR #73 which adds the scan_iter function as well as allows cursor to be a string.

**Comment by jamesls** [comment]
Closing, this is superceded by #73 which has been merged.

**Pull request closed without merging**
