### PR TITLE
Add support for decode_responses

### PR DESCRIPTION
**Pull request by jjackson26**
Implementation for decoding responses as requested in #77.

### CODE REVIEW

**Comment by rantonmattei** [comment]
@jamesls Any chance we can have this one merged?

FYI @jjackson26

**Comment by matt-snider** [comment]
Yes this would be very useful to have! Any updates on this?

**Comment by Korijn** [comment]
Can this be merged in @jamesls? We need the fix for windows as well...

**Comment by Korijn** [comment]
@jamesls Rebased this in #116 so it can be merged more easily. All CI checks pass.

**Comment by jamesls** [comment]
Fixed in https://github.com/jamesls/fakeredis/pull/123.  Thanks everyone.

**Pull request closed without merging**
