### PR TITLE
Rename assertRaisesRegexp to assertRaisesRegex, closes #241

### LINKED ISSUE #241: DeprecationWarning of assertRaisesRegexp in test_fakeredis.py
```
test_fakeredis.py:3621: DeprecationWarning: Please use assertRaisesRegex instead.
  redis.ResponseError, 'value is not an integer or out of range'):
```

### PR DESCRIPTION
**Pull request by isms**
Reference: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegex

### CODE REVIEW

**Comment by bmerry** [comment]
This is failing all the Travis tests.

**Comment by isms** [comment]
@bmerry Oddly they pass locally with Python 3.6. I'm not sure what the issue is.

**Comment by bmerry** [comment]
The old assertRaisesRegexp spelling is the only version supported in Python 2 (and presumably why Python 3 still supports it). Is the deprecation warning causing issues anywhere? Since it's only in the test code I'd prefer to leave it as is rather than adding complexity. Once Python 2 reaches end-of-life I plan to remove Python 2 support and at that time it could be addressed.

**Comment by isms** [comment]
Fair enough, seems like a good plan for backwards compatibility until 2.7
EOL.

**Comment by adamantike** [comment]
@isms can you reopen this PR, and update it by using [`six.assertRaisesRegex`](https://six.readthedocs.io/#six.assertRaisesRegex)?

**Pull request closed without merging**
