### PR TITLE
[rebased] Add support for decode_responses=True

### PR DESCRIPTION
**Pull request by Korijn**
This is a rebased version of #82.

### CODE REVIEW

**Comment by bersace** [comment]
:up: Great contribution ! I need it here too.

**Comment by jamesls** [comment]
Thanks for the pull request, and thanks for rebasing.  My only hesitation with this pull request is that it's fairly invasive and touches just about every method.  I wonder if there's a more succinct way to do this?  My other concern is how likely it's going to be that any new methods/ops added in the future will miss a `_decode_response()` call.  If the tests pass for a new method without requiring a `_decode_response()` call, it seems like this will be something that's easy to miss?

I'm not opposed to this pull request as is, but would like to hear other's thoughts first.

**Comment by Korijn** [comment]
We might be able to move part of the code into `_StrKeyDict`? It won't cover all of it though.

**Comment by matt-snider** [comment]
Hi, two major points where the implementation could be improved:

1. The decode methods are unnecessarily re-declared on every single call to `_decode_response()`. Is there any reason for this?
2. The tests are too simple. They should re-use the existing tests, taking into account `decode_responses`.

I'm currently trying to implement a less invasive method, but it's a bit tricky.

**Comment by jamesls** [comment]
Resolved via https://github.com/jamesls/fakeredis/pull/123 .  Thanks everyone for looking into this.

**Pull request closed without merging**
